#!/usr/bin/env Rscript
#
# Compare two vintages of the index and report what moved.
#
# Unreviewed rank churn is how an index loses credibility, so this exists to
# make movement impossible to miss before it is published. It reports rather
# than decides: thresholds come from config/validation.yml when present, and
# the exit code says whether anything exceeded them.
#
# Usage:
#   Rscript scripts/30_diff_outputs.R --before <dir> --after <dir>
#                                     [--out <path>] [--top-n 15]
#
# <dir> is an outputs/ directory from a pipeline run.
#
# Exit codes:
#   0  every delta within tolerance
#   1  at least one delta outside tolerance, or coverage changed
#   2  the comparison could not be made (missing files, no shared geographies)

suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
})

args <- commandArgs(trailingOnly = TRUE)
arg_value <- function(flag, default = NULL) {
  hit <- which(args == flag)
  if (length(hit) == 0 || hit[1] == length(args)) default else args[hit[1] + 1]
}

before_dir <- arg_value("--before")
after_dir <- arg_value("--after")
if (is.null(before_dir) || is.null(after_dir)) {
  stop("both --before and --after are required", call. = FALSE)
}
out_path <- arg_value("--out", NULL)
top_n <- as.integer(arg_value("--top-n", "15"))

repo_root <- normalizePath(
  file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])), ".."),
  winslash = "/", mustWork = FALSE
)
if (is.na(repo_root) || !dir.exists(repo_root)) repo_root <- getwd()

# Tolerances. config/validation.yml is the intended home (Phase 2); these are
# the defaults until it exists, and they are deliberately loose enough not to
# flag floating-point noise and tight enough to catch a real shift.
tol <- list(index_abs = 0.02, subindex_abs = 0.05, rank_positions = 3L)
vpath <- file.path(repo_root, "config", "validation.yml")
if (file.exists(vpath) && requireNamespace("yaml", quietly = TRUE)) {
  cfg <- yaml::read_yaml(vpath)$diff %||% NULL
  if (!is.null(cfg)) tol <- utils::modifyList(tol, cfg)
}
`%||%` <- function(x, y) if (!is.null(x)) x else y

read_state <- function(dir) {
  p <- file.path(dir, "Electro-Industrial_state.csv")
  if (!file.exists(p)) return(NULL)
  suppressWarnings(read_csv(p, show_col_types = FALSE, progress = FALSE))
}

a <- read_state(before_dir)
b <- read_state(after_dir)
if (is.null(a) || is.null(b)) {
  cat("diff_outputs: Electro-Industrial_state.csv missing from one side; cannot compare\n")
  quit(status = 2)
}

sub_indices <- intersect(
  c("deployment_index", "infra_index", "econ_index", "intent_index", "cluster_index", "ease_index"),
  intersect(names(a), names(b))
)
composite <- intersect(c("Electro_Industrial_index_w", "Electro_Industrial_index"), intersect(names(a), names(b)))

entered <- setdiff(b$state, a$state)
left <- setdiff(a$state, b$state)
shared <- intersect(a$state, b$state)
if (length(shared) == 0) {
  cat("diff_outputs: no shared geographies; cannot compare\n")
  quit(status = 2)
}

A <- a[match(shared, a$state), ]
B <- b[match(shared, b$state), ]

rank_of <- function(df, col) rank(-df[[col]], ties.method = "min", na.last = "keep")

lines <- c(
  "<!-- Generated by scripts/30_diff_outputs.R. Do not edit by hand. -->",
  "", "# Output diff", "",
  paste0("`", before_dir, "` &rarr; `", after_dir, "`"), ""
)

breached <- FALSE
note <- function(...) lines <<- c(lines, paste0(...))

# ---- coverage ------------------------------------------------------------
if (length(entered) > 0 || length(left) > 0) {
  breached <- TRUE
  note("## Coverage changed", "")
  if (length(entered) > 0) note("- **entered:** ", paste(entered, collapse = ", "))
  if (length(left) > 0) note("- **left:** ", paste(left, collapse = ", "))
  note("")
}

# ---- headline ------------------------------------------------------------
note("## Summary", "")
note("| column | n changed | mean |&Delta;| | max |&Delta;| | geography at max | within tolerance |")
note("|---|---|---|---|---|---|")

summarise_col <- function(col, limit) {
  d <- B[[col]] - A[[col]]
  d[is.na(d)] <- 0
  changed <- sum(abs(d) > 1e-12)
  mx <- if (length(d)) max(abs(d)) else 0
  who <- if (length(d) && mx > 0) shared[which.max(abs(d))] else "&mdash;"
  ok <- mx <= limit
  if (!ok) breached <<- TRUE
  note(
    "| `", col, "` | ", changed, " | ",
    sprintf("%.4f", mean(abs(d))), " | ", sprintf("%.4f", mx), " | ", who, " | ",
    if (ok) "yes" else paste0("**NO** (limit ", limit, ")"), " |"
  )
  invisible(d)
}

for (col in composite) summarise_col(col, tol$index_abs)
for (col in sub_indices) summarise_col(col, tol$subindex_abs)
note("")

# ---- rank movement -------------------------------------------------------
if (length(composite) > 0) {
  key <- composite[1]
  ra <- rank_of(A, key)
  rb <- rank_of(B, key)
  moved <- tibble(
    state = shared,
    rank_before = ra, rank_after = rb,
    rank_change = ra - rb,
    value_before = A[[key]], value_after = B[[key]]
  ) %>%
    filter(!is.na(rank_change), rank_change != 0) %>%
    arrange(desc(abs(rank_change)))

  big <- moved %>% filter(abs(rank_change) > tol$rank_positions)
  if (nrow(big) > 0) breached <- TRUE

  note("## Rank movement on `", key, "`", "")
  note(
    nrow(moved), " of ", length(shared), " geographies changed rank; ",
    nrow(big), " moved more than ", tol$rank_positions, " positions."
  )
  note("")
  if (nrow(moved) > 0) {
    note("| geography | before | after | change | value before | value after |")
    note("|---|---|---|---|---|---|")
    for (i in seq_len(min(top_n, nrow(moved)))) {
      r <- moved[i, ]
      note(
        "| ", r$state, " | ", r$rank_before, " | ", r$rank_after, " | ",
        sprintf("%+d", r$rank_change), " | ",
        sprintf("%.4f", r$value_before), " | ", sprintf("%.4f", r$value_after), " |"
      )
    }
    note("")
  }
}

# ---- what drove it -------------------------------------------------------
# Coverage change per indicator is usually the real story: an indicator going
# from 3 populated geographies to 35 moves everything downstream of it.
cov <- function(dir) {
  p <- file.path(dir, "..", "data", "processed", "inputs_processed.csv")
  if (!file.exists(p)) return(NULL)
  d <- suppressWarnings(read_csv(p, show_col_types = FALSE, progress = FALSE))
  vapply(d, function(x) sum(!is.na(x)), integer(1))
}
ca <- cov(before_dir); cb <- cov(after_dir)
if (!is.null(ca) && !is.null(cb)) {
  common <- intersect(names(ca), names(cb))
  delta <- cb[common] - ca[common]
  delta <- delta[delta != 0]
  if (length(delta) > 0) {
    note("## Input coverage changes", "")
    note("| indicator | populated before | populated after | change |")
    note("|---|---|---|---|")
    for (nm in names(sort(delta, decreasing = TRUE))) {
      note("| `", nm, "` | ", ca[[nm]], " | ", cb[[nm]], " | ", sprintf("%+d", delta[[nm]]), " |")
    }
    note("")
  }
}

note("---", "")
note(
  if (breached) {
    "**Outside tolerance.** This needs human sign-off before publication."
  } else {
    "**Within tolerance** on every compared column."
  }
)

txt <- paste(lines, collapse = "\n")
if (!is.null(out_path)) {
  dir.create(dirname(out_path), showWarnings = FALSE, recursive = TRUE)
  writeLines(lines, out_path)
  cat("diff_outputs: wrote ", out_path, "\n", sep = "")
}
cat(txt, "\n", sep = "")

quit(status = if (breached) 1L else 0L)
